# Generated by Django 4.2.30 on 2026-09-29 09:07

import apps.queue.keys
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('counsellors', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('centres', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TokenSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_number', models.PositiveIntegerField(default=0)),
                ('centre', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='token_sequence', to='centres.centre')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=16)),
                ('source', models.CharField(choices=[('self', 'Self check-in'), ('desk', 'Front desk')], default='self', max_length=4)),
                ('status', models.CharField(choices=[('waiting', 'Waiting'), ('called', 'Called'), ('in_session', 'In session'), ('done', 'Done'), ('no_show', 'No-show'), ('released', 'Released'), ('not_counselled', 'Not counselled')], default='waiting', max_length=16)),
                ('name', models.CharField(max_length=120)),
                ('school', models.CharField(blank=True, max_length=200)),
                ('mobile', models.CharField(max_length=10)),
                ('parent_mobile', models.CharField(blank=True, max_length=10)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('stream', models.CharField(choices=[('PCM', 'Science – PCM'), ('PCB', 'Science – PCB'), ('PCMB', 'Science – PCMB'), ('COM', 'Commerce'), ('HUM', 'Humanities / Arts'), ('OTH', 'Other')], max_length=4)),
                ('klass', models.CharField(blank=True, choices=[('Class 11', 'Class 11'), ('Class 12', 'Class 12'), ('Dropper / repeat year', 'Dropper / repeat year'), ('Graduate', 'Graduate'), ('Parent enquiring', 'Parent enquiring')], max_length=24)),
                ('course', models.CharField(blank=True, max_length=200)),
                ('exams', models.JSONField(blank=True, default=list)),
                ('clarity', models.CharField(blank=True, choices=[('Very clear', 'Very clear'), ('Have shortlisted options', 'Have shortlisted options'), ('Need help shortlisting', 'Need help shortlisting'), ('Completely confused', 'Completely confused')], max_length=32)),
                ('help', models.JSONField(blank=True, default=list)),
                ('consent', models.CharField(choices=[('given', 'Given'), ('pending', 'Pending')], default='pending', max_length=8)),
                ('consent_at', models.DateTimeField(blank=True, null=True)),
                ('checkin_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('queue_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('priority', models.IntegerField(default=0)),
                ('called_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('recalls', models.PositiveSmallIntegerField(default=0)),
                ('rating', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('outcome', models.CharField(blank=True, choices=[('ready', 'Ready to apply'), ('interested', 'Interested, needs time'), ('exploring', 'Just exploring'), ('not_fit', 'Not a fit')], max_length=12, null=True)),
                ('follow_up_on', models.DateField(blank=True, null=True)),
                ('colleges_discussed', models.TextField(blank=True)),
                ('home_city', models.CharField(blank=True, max_length=100)),
                ('target_exam', models.CharField(blank=True, max_length=100)),
                ('budget', models.CharField(blank=True, max_length=60)),
                ('accompanied_by', models.CharField(blank=True, max_length=100)),
                ('access_key', models.CharField(default=apps.queue.keys.make_access_key, editable=False, max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('centre', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='students', to='centres.centre')),
                ('consent_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='counsellors.counsellor')),
                ('counsellor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='students', to='counsellors.counsellor')),
            ],
            options={
                'ordering': ['-checkin_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='SessionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('called_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField()),
                ('outcome', models.CharField(blank=True, choices=[('ready', 'Ready to apply'), ('interested', 'Interested, needs time'), ('exploring', 'Just exploring'), ('not_fit', 'Not a fit')], max_length=12, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('centre', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='session_records', to='centres.centre')),
                ('counsellor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='session_records', to='counsellors.counsellor')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_records', to='queue.student')),
            ],
            options={
                'ordering': ['ended_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('author_name', models.CharField(max_length=120)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notes', to='counsellors.counsellor')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='queue.student')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verb', models.CharField(choices=[('checked_in', 'Checked In'), ('called', 'Called'), ('started', 'Started'), ('completed', 'Completed'), ('missed', 'Missed'), ('no_show', 'No Show'), ('released', 'Released'), ('requeued', 'Requeued'), ('moved', 'Moved'), ('pulled_forward', 'Pulled Forward'), ('consent_given', 'Consent Given'), ('edited', 'Edited'), ('noted', 'Noted'), ('rated', 'Rated'), ('message_failed', 'Message Failed'), ('centre_live', 'Centre Live'), ('centre_closed', 'Centre Closed'), ('exported', 'Exported')], max_length=20)),
                ('at', models.DateTimeField(default=django.utils.timezone.now)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to=settings.AUTH_USER_MODEL)),
                ('centre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_events', to='centres.centre')),
                ('on_behalf_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='counsellors.counsellor')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audit_events', to='queue.student')),
            ],
            options={
                'ordering': ['at', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['centre', 'status'], name='queue_stude_centre__299254_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['centre', 'mobile'], name='queue_stude_centre__9e7612_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['counsellor', 'status', 'queue_at'], name='queue_stude_counsel_755a59_idx'),
        ),
        migrations.AddConstraint(
            model_name='student',
            constraint=models.UniqueConstraint(fields=('centre', 'token'), name='student_unique_token_per_centre'),
        ),
        migrations.AddConstraint(
            model_name='student',
            constraint=models.CheckConstraint(check=models.Q(('rating__isnull', True), models.Q(('rating__gte', 1), ('rating__lte', 5)), _connector='OR'), name='student_rating_1_to_5'),
        ),
        migrations.AddIndex(
            model_name='sessionrecord',
            index=models.Index(fields=['centre', 'counsellor', 'ended_at'], name='queue_sessi_centre__fddeab_idx'),
        ),
        migrations.AddConstraint(
            model_name='note',
            constraint=models.CheckConstraint(check=models.Q(('text', ''), _negated=True), name='note_text_not_empty'),
        ),
        migrations.AddIndex(
            model_name='auditevent',
            index=models.Index(fields=['centre', 'at'], name='queue_audit_centre__c21285_idx'),
        ),
        migrations.AddIndex(
            model_name='auditevent',
            index=models.Index(fields=['student', 'at'], name='queue_audit_student_397351_idx'),
        ),
    ]
