# Generated by Django 4.2.30 on 2026-09-29 09:27

import apps.queue.keys
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def backfill_session_queue_at(apps, schema_editor):
    """Existing rows predate the snapshot: use the student's queue_at, else the call/start time."""
    SessionRecord = apps.get_model("queue", "SessionRecord")
    for record in SessionRecord.objects.filter(queue_at__isnull=True).select_related("student"):
        record.queue_at = record.student.queue_at or record.called_at or record.started_at
        record.save(update_fields=["queue_at"])


class Migration(migrations.Migration):

    dependencies = [
        ('centres', '0002_schema_protect_constraints'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('counsellors', '0002_schema_protect_constraints'),
        ('queue', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionrecord',
            name='queue_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.RunPython(backfill_session_queue_at, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='sessionrecord',
            name='queue_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='auditevent',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='audit_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='auditevent',
            name='centre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='audit_events', to='centres.centre'),
        ),
        migrations.AlterField(
            model_name='auditevent',
            name='on_behalf_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='counsellors.counsellor'),
        ),
        migrations.AlterField(
            model_name='auditevent',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='audit_events', to='queue.student'),
        ),
        migrations.AlterField(
            model_name='note',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='notes', to='counsellors.counsellor'),
        ),
        migrations.AlterField(
            model_name='note',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notes', to='queue.student'),
        ),
        migrations.AlterField(
            model_name='sessionrecord',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='session_records', to='queue.student'),
        ),
        migrations.AlterField(
            model_name='student',
            name='access_key',
            field=models.CharField(db_collation='utf8mb4_bin', default=apps.queue.keys.make_access_key, editable=False, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='consent_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='counsellors.counsellor'),
        ),
        migrations.AlterField(
            model_name='tokensequence',
            name='centre',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='token_sequence', to='centres.centre'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['centre', 'checkin_at'], name='queue_stude_centre__a2dee6_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['checkin_at'], name='queue_stude_checkin_e6e6a2_idx'),
        ),
        migrations.AddConstraint(
            model_name='sessionrecord',
            constraint=models.CheckConstraint(check=models.Q(('ended_at__gte', models.F('started_at'))), name='sessionrecord_ends_after_start'),
        ),
    ]
