# Generated by Django 4.2.30 on 2026-09-29 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queue', '0002_schema_protect_constraints'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditevent',
            name='verb',
            field=models.CharField(choices=[('checked_in', 'Checked In'), ('called', 'Called'), ('started', 'Started'), ('completed', 'Completed'), ('missed', 'Missed'), ('no_show', 'No Show'), ('released', 'Released'), ('requeued', 'Requeued'), ('moved', 'Moved'), ('pulled_forward', 'Pulled Forward'), ('consent_given', 'Consent Given'), ('edited', 'Edited'), ('noted', 'Noted'), ('rated', 'Rated'), ('message_failed', 'Message Failed'), ('centre_live', 'Centre Live'), ('centre_closed', 'Centre Closed'), ('duty_changed', 'Duty Changed'), ('exported', 'Exported')], max_length=20),
        ),
    ]
