# Generated by Django 4.2.30 on 2026-09-29 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Centre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('venue', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('opens_at', models.TimeField()),
                ('closes_at', models.TimeField()),
                ('expected_students', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('live', 'Live'), ('closed', 'Closed')], default='planned', max_length=10)),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('front_desk_phone', models.CharField(blank=True, max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['date', 'city'],
            },
        ),
        migrations.CreateModel(
            name='CentreSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_session_min', models.PositiveSmallIntegerField(default=15)),
                ('wait_sla_min', models.PositiveSmallIntegerField(default=30)),
                ('recall_limit', models.PositiveSmallIntegerField(default=2)),
                ('whatsapp_enabled', models.BooleanField(default=True)),
                ('centre', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='centres.centre')),
            ],
            options={
                'verbose_name_plural': 'centre settings',
            },
        ),
        migrations.AddIndex(
            model_name='centre',
            index=models.Index(fields=['date', 'status'], name='centres_cen_date_997701_idx'),
        ),
        migrations.AddIndex(
            model_name='centre',
            index=models.Index(fields=['city', 'date'], name='centres_cen_city_4a53a7_idx'),
        ),
        migrations.AddConstraint(
            model_name='centre',
            constraint=models.CheckConstraint(check=models.Q(('closes_at__gt', models.F('opens_at'))), name='centre_closes_after_opens'),
        ),
    ]
