# Generated by Django 4.2.30 on 2026-09-29 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('centres', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='centresettings',
            name='centre',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='settings', to='centres.centre'),
        ),
        migrations.AddConstraint(
            model_name='centresettings',
            constraint=models.CheckConstraint(check=models.Q(('recall_limit__gte', 1)), name='centresettings_recall_limit_gte_1'),
        ),
        migrations.AddConstraint(
            model_name='centresettings',
            constraint=models.CheckConstraint(check=models.Q(('target_session_min__gte', 1)), name='centresettings_target_session_gte_1'),
        ),
        migrations.AddConstraint(
            model_name='centresettings',
            constraint=models.CheckConstraint(check=models.Q(('wait_sla_min__gte', 1)), name='centresettings_wait_sla_gte_1'),
        ),
    ]
