# Generated by Django 4.2.30 on 2026-09-29 09:07

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('queue', '0001_initial'),
        ('centres', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtpCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(max_length=10)),
                ('code_hash', models.CharField(max_length=128)),
                ('expires_at', models.DateTimeField()),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('invalidated_at', models.DateTimeField(blank=True, null=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('verification_nonce', models.CharField(blank=True, max_length=64)),
                ('verification_used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('centre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='otp_codes', to='centres.centre')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['centre', 'mobile', 'created_at'], name='messaging_o_centre__fbd0d0_idx'), models.Index(fields=['verification_nonce'], name='messaging_o_verific_b134d4_idx')],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template', models.CharField(choices=[('otp_code', 'OTP code'), ('token_confirm_self', 'Token confirmation'), ('token_confirm_desk', 'Token confirmation (front desk)'), ('consent_request', 'Consent request'), ('turn_called', 'Turn alert'), ('missed_first', 'First missed call'), ('missed_final', 'Final missed call'), ('desk_changed', 'Desk change'), ('released', 'Token released'), ('session_done', 'Session complete')], max_length=24)),
                ('to', models.CharField(max_length=10)),
                ('body', models.TextField()),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('failed', 'Failed')], default='queued', max_length=10)),
                ('provider_id', models.CharField(blank=True, max_length=100)),
                ('failure_reason', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='queue.student')),
            ],
            options={
                'ordering': ['created_at', 'id'],
                'indexes': [models.Index(fields=['student', 'template', 'status'], name='messaging_m_student_4a4f7d_idx'), models.Index(fields=['provider_id'], name='messaging_m_provide_141d30_idx')],
            },
        ),
    ]
