# Generated by Django 4.2.30 on 2026-09-29 09:27

from django.db import migrations, models
import django.db.models.deletion


def blank_nonces_to_null(apps, schema_editor):
    """'' meant "not verified yet"; it must become NULL before the column turns UNIQUE."""
    apps.get_model("messaging", "OtpCode").objects.filter(verification_nonce="").update(verification_nonce=None)


class Migration(migrations.Migration):

    dependencies = [
        ('queue', '0002_schema_protect_constraints'),
        ('centres', '0002_schema_protect_constraints'),
        ('messaging', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='otpcode',
            name='messaging_o_verific_b134d4_idx',
        ),
        migrations.AlterField(
            model_name='message',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='messages', to='queue.student'),
        ),
        migrations.AlterField(
            model_name='message',
            name='to',
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name='otpcode',
            name='centre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='otp_codes', to='centres.centre'),
        ),
        migrations.AlterField(
            model_name='otpcode',
            name='code_hash',
            field=models.CharField(db_collation='utf8mb4_bin', max_length=128),
        ),
        # Split on purpose: Django 4.2 on MySQL drops COLLATE when nullability and collation change in one
        # AlterField (it emits a second bare `MODIFY ... NULL`). 1) nullable, 2) '' -> NULL, 3) binary
        # collation, 4) unique.
        migrations.AlterField(
            model_name='otpcode',
            name='verification_nonce',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.RunPython(blank_nonces_to_null, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='otpcode',
            name='verification_nonce',
            field=models.CharField(blank=True, db_collation='utf8mb4_bin', max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='otpcode',
            name='verification_nonce',
            field=models.CharField(blank=True, db_collation='utf8mb4_bin', max_length=64, null=True, unique=True),
        ),
    ]
