# Generated by Django 4.2.30 on 2026-09-29 09:07

import apps.accounts.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('counsellors', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('centres', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=254, unique=True)),
                ('failed_count', models.PositiveIntegerField(default=0)),
                ('last_failed_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StaffUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('role', models.CharField(choices=[('ops_lead', 'Ops lead'), ('reception', 'Front desk'), ('counsellor', 'Counsellor')], max_length=12)),
                ('title', models.CharField(blank=True, max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('centre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff', to='centres.centre')),
                ('counsellor', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user', to='counsellors.counsellor')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'ordering': ['name'],
            },
            managers=[
                ('objects', apps.accounts.models.StaffUserManager()),
            ],
        ),
        migrations.AddConstraint(
            model_name='staffuser',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('role', 'counsellor'), _negated=True), ('counsellor__isnull', False), _connector='OR'), name='staffuser_counsellor_has_counsellor'),
        ),
        migrations.AddConstraint(
            model_name='staffuser',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('role', 'reception'), _negated=True), ('centre__isnull', False), _connector='OR'), name='staffuser_reception_has_centre'),
        ),
    ]
