# Generated by Django 4.2.30 on 2026-09-29 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('centres', '0002_schema_protect_constraints'),
        ('counsellors', '0002_schema_protect_constraints'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffuser',
            name='centre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='staff', to='centres.centre'),
        ),
        migrations.AlterField(
            model_name='staffuser',
            name='counsellor',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user', to='counsellors.counsellor'),
        ),
    ]
