# Generated by Django 4.2.30 on 2026-09-29 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('centres', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Counsellor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('mobile', models.CharField(max_length=10)),
                ('streams', models.JSONField(default=list)),
                ('expected_session_min', models.PositiveSmallIntegerField(default=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Posting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desk_label', models.CharField(max_length=40)),
                ('duty', models.CharField(choices=[('on_desk', 'On desk'), ('on_break', 'On break'), ('off_duty', 'Off duty')], default='off_duty', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('centre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postings', to='centres.centre')),
                ('counsellor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='postings', to='counsellors.counsellor')),
            ],
            options={
                'ordering': ['centre_id', 'desk_label'],
                'indexes': [models.Index(fields=['centre', 'duty'], name='counsellors_centre__98b407_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='posting',
            constraint=models.UniqueConstraint(fields=('centre', 'desk_label'), name='posting_unique_desk_per_centre'),
        ),
        migrations.AddConstraint(
            model_name='posting',
            constraint=models.UniqueConstraint(fields=('counsellor', 'centre'), name='posting_unique_counsellor_per_centre'),
        ),
    ]
