# Generated by Django 4.2.30 on 2026-09-29 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('centres', '0002_schema_protect_constraints'),
        ('counsellors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posting',
            name='centre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='postings', to='centres.centre'),
        ),
        migrations.AddConstraint(
            model_name='counsellor',
            constraint=models.CheckConstraint(check=models.Q(('expected_session_min__gte', 1)), name='counsellor_expected_session_gte_1'),
        ),
    ]
